logging:
  level:
    com.example.club: DEBUG
    com.example.club.mapper: TRACE

debug: true

server:
  port: 8080

spring:
  application:
    name: "Club_Alliance"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "123456"
    url: "jdbc:mysql://localhost:3306/club_alliance?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
