server:
  port: 8080

spring:
  application:
    name: "Club_Alliance"
  datasource:
    url: jdbc:mysql://localhost:3306/club_alliance?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
