server:
  port: 8080

spring:
  application:
    name: "Club_Alliance"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: hzs07280104
    url: "jdbc:mysql://localhost:3306/club_alliance?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.example.club.handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    map-underscore-to-camel-case: true
